### ISSUE TITLE
最新的包，从Wayland 切到 Xorg 环境下时，会崩溃

### ISSUE THREAD

**Issue by yanhuacuo** [hchunhui/ibus-rime.AppImage#5]
大佬排查一下，我这里是 Ubuntu22.04-LTS

**Comment by hchunhui** [comment]
下载了 ubuntu 22.04.1 live CD 测试，除了现在需要手动安装 libfuse2 以外，看起来都正常。包括 Wayland 和 X11 都没有复现崩溃的情况

**Comment by yanhuacuo** [comment]
> 下载了 ubuntu 22.04.1 live CD 测试，除了现在需要手动安装 libfuse2 以外，看起来都正常。包括 Wayland 和 X11 都没有复现崩溃的情况

进入过 Wayland 环境后，「注销」登录，在登入界面的「右下角」选「Xorg」进入，则会崩掉，而且自此次一崩之后，再也不能进入 「Xorg」了。

我这里是物理装机，稍后我给您发一下崩溃界面的报错信息。

**Comment by yanhuacuo** [comment]
找到原因了，可能是因为我在 profile 中添加了启动 ibus-rime 的命令导致的，清除掉这个启动语句后就正常了，在 X11 和 Wayland 下互切也没有复现下面的故障：

（加启动语句，是之前有过开机后 ibus-rime 没有成功启动的先例）

![pic](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/81ae08e75112878ade80fbcb7953ada5.jpg)

**Comment by hchunhui** [comment]
这个包应该是不需要在 profile 里面反复运行的，但为什么会导致崩溃不得而知。
另外刚才我试着解决了一下ubuntu 22.04以后需要装 libfuse2 的问题。现在新编译的包应该是可以不依赖 fuse2，开箱即用了。

**Comment by yanhuacuo** [comment]
> 这个包应该是不需要在 profile 里面反复运行的，但为什么会导致崩溃不得而知。 另外刚才我试着解决了一下ubuntu 22.04以后需要装 libfuse2 的问题。现在新编译的包应该是可以不依赖 fuse2，开箱即用了。

如果仅用「Wayland」环境，那么类似「开机启动项」一样在「profile」中添加「启动命令」也是没有问题的（没有实例冲突），但是忽然切到 Xorg 环境里，它就崩了……猜想是进入 Xorg 环境时，输入法项需要更多系统库或接口来配合才能启动，从 profile 那里就开始唤醒，过早了。这也能解释去除 profile 里的唤醒代码后，一切如常。也不一定对，不过，排除掉问题就行了。

 libfuse2 这个问题，好像是 AppImage 打包机制的事情，现在的发行版内置的都是  libfuse3 之类的更新的版本。只要与 AppImage 类的包打交道，迟早都要往系统里装一个。
